### ISSUE TITLE
How to start program

### ISSUE THREAD

**Issue by Lonce32** [ringrunnermg/Ringcon-Driver#1]
Hello, it says I have to run the "program" and "tick" certain boxes to use Ringcon-Driver. Where do I go to start this program after downloading the code.

**Comment by ringrunnermg** [comment]
Are the instruction in the Readme not clear?

    Download the latest version from the releases tab https://github.com/ringrunnermg/Ringcon-Driver/releases/tag/1.0.1
    Download the latest version of Vigembus from https://github.com/ViGEm/ViGEmBus/releases and install it
    Connect the controllers (info below)
    Run the program, this should set up a virtual x360 controller on your computer.

The 1.0.1 release is a zip file of the release which has "Ringcon driver.exe" in it.

**Comment by Lonce32** [comment]
I ran the program, thank you!
