### ISSUE TITLE
Work's in "debug mode" but dosen't work with unity

### ISSUE THREAD

**Issue by Lonce32** [ringrunnermg/Ringcon-Driver#3]
Hello, Thank you for this cool program.

I've been trying to get the ringcon driver to work with unity projects.

I tested the ringcon in mode 1 and 2 in the debug mode, and it is registering motion controls but when I try to test it in my own unity projects, the ringcordion unity project or an online controller tester, it doesn't register any inputs.

Any suggestions or anything to help me, would be appreciated.

**Comment by ringrunnermg** [comment]
Hi, sounds like its almost there, it is just missing the conversion to xinput step. Can you make sure that Vigembus is installed correctly as this is what the driver relies on for the conversion.

**Comment by Lonce32** [comment]
I've extracted the zip file, but I haven't done anything with those files.

**Comment by ringrunnermg** [comment]
https://github.com/ViGEm/ViGEmBus/releases

Follow the instructions to install Vigembus then you should be good to go.

**Comment by Lonce32** [comment]
I've downloaded it but I haven't ran the program. I don't really seem to understand if I have to run the program and if I do where that program is located in the files. All that the publisher says is that I have to download it (which I did) and then click through it (I have no idea what that means). Sorry if this comment was confusing.

**Comment by ringrunnermg** [comment]
I'm not sure what you mean. On the releases link above download ViGEmBusSetup_x64.msi (or ViGEmBusSetup_x86.msi if you have 32bit windows). When you run it it will automatically do the setup and put the Vigem stuff in the right place.

**Comment by Lonce32** [comment]
I've downloaded the Vigembus setup so I'm pretty sure I've done everything correctly.

**Comment by Lonce32** [comment]
I went on the VigemBus support discord server and got VigemBus going correctly, it now works. Thank you!
