### ISSUE TITLE
Successfully initialized but no Ringcon detected Joy-Con (R)!

### ISSUE THREAD

**Issue by cooperate** [ringrunnermg/Ringcon-Driver#7]
Followed the installation steps.  Joy-Con's are connected via bluetooth and the ringcon is attached to the right Joy-Con but it keeps giving me this error.

Full log:
```
Found joycon L: e0f6b573fd57 \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002057e_pid&2006#a&5702fc4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Found joycon R: e0f6b573db85 \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002057e_pid&2007#a&7d1a595&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
Enabling vibration...
Enabling IMU data...
Set input report mode to 0x30...
Getting calibration data...
Successfully initialized Joy-Con (L)!
Enabling vibration...
Enabling IMU data...
Set input report mode to 0x30...
Getting calibration data...
Enabling MCU data 22 1
Enabling MCU data 22 1
Enabling MCU data 22 1
Enabling MCU data 21 21 0 3...
Enabling MCU data 21 21 0 3...
Enabling MCU data 21 21 0 3...
Enabling MCU data 21 21 0 3...
Enabling MCU data 21 21 1 1...
Enabling MCU data 21 21 1 1...
Enabling MCU data 21 21 1 1...
Enabling MCU data 21 21 1 1...
Get ext data 59..Enabling IMU data...
Successfully initialized but no Ringcon detected Joy-Con (R)!
setting LEDs...
vibrating JoyCon(s).
Done.

```

**Comment by ringrunnermg** [comment]
Hey Cooperate! You were one of the earlier ones to find the driver. Were you able to try the initial versions to see if the problem is only happening with the latest one?

First the basic checks: Have you made sure your Joycons have the latest update and that the Ringcon works in Ring Fit Adventure?

**Comment by cooperate** [comment]
> Hey Cooperate! You were one of the earlier ones to find the driver. Were you able to try the initial versions to see if the problem is only happening with the latest one?
> 
> First the basic checks: Have you made sure your Joycons have the latest update and that the Ringcon works in Ring Fit Adventure?

Yep!  

EDIT: Sorry to expand on this I've tried both 1.0.3 and 1.0.2 and neither can connect to the ringcon.  As you can see by the logs though, the joycons connect fine.

**Comment by cooperate** [comment]
This issue was resolved by updating Joy-Cons to the latest firmware and ensuring no background-programs that may overtake xinput behavior (like Steam) were running.

**Comment by ringrunnermg** [comment]
Glad you got it going, it had me stumped.

**Comment by xgdgsc** [comment]
My Joycon(R) disconnects very frequently. Don' t know is 's a joycon issue or bluetooth adapter issue. Joycon(R) connects very stable.
